### Get Request all courses
GET http://localhost:8000/api/v1/courses/ HTTP/1.1

### Get single course
GET http://localhost:8000/api/v1/courses/5d725cb9c4ded7bcb480eaa1/ HTTP/1.1


### POST Request
POST http://localhost:8000/api/v1/bootcamps/5d725a1b7b292f5f8ceff788/courses/ HTTP/1.1
content-type: application/json

{
		"title": "Full Stack Web Dev 3",
		"description": "In this course you will learn all about the front end with HTML, CSS a...r",
		"weeks": 10,
		"tuition": 100000,
		"minimumSkill": "intermediate",
		"scholarshipAvailable": false
}

### PUT Request
PUT http://localhost:8000/api/v1/courses/5d725cb9c4ded7bcb480eaa1 HTTP/1.1
content-type: application/json

{
		"title": "Full Stack Web Dev",
		"description": "In this course you will learn all about the front end with HTML, CSS a...r",
		"weeks": 10,
		"tuition": 13000,
		"minimumSkill": "advanced",
		"scholarshipAvailable": false
}

### DELETE Request
DELETE http://localhost:8000/api/v1/courses/619720466815c09b768b0df9 HTTP/1.1